### ISSUE TITLE
Tile Layer style options (brightness/saturation/contrast) do not update before event is sent

### ISSUE THREAD

**Issue by jkae** [ngageoint/opensphere#1046]
Let's say I have an `AbstractWebGLSynchronizer` configured for `os.layer.Tile` with a style change listener setup this way:

```
const STYLE_KEYS_ = [
  'change:brightness',
  ...etc...
];
... some code ...
events.listenEach(this.layer, STYLE_KEYS_, this.onStyleChange_, this);
... etc ...

  onStyleChange_(event) {
    console.log('old: ' + event.oldValue);
    switch (event.type) {
      case 'change:opacity':
        console.log('o: ' + this.layer.getOpacity());
        break;
      case 'change:brightness':
        console.log(b: ' + this.layer.getBrightness());
        break;
      case 'change:saturation':
        console.log('s: ' + this.layer.getSaturation());
        break;
      case 'change:contrast':
        console.log('c: ' + this.layer.getContrast());
        break;
      default:
        break;
    }
  }
```

I would expect the old value to be different from the value returned by the first `get` call. For opacity, this works as I move the slider or click to a different position:
```
old: 1
o: 0.95
old: 0.95
o: 0.9
old: 0.9
o: 0.85
old: 0.85
o: 0.5
```
For every other style option (contrast represented), the post-event value is the same as the old value:
```
old: 0.5
c: 0.5
old: 0.55
c: 0.55
old: 1.2
c: 1.2
old: 1.25
c: 1.25
old: 1.75
c: 1.75
old: 0.5
c: 0.5
```
For rendering my tiles, I'm changing their coloration in a shader rather than retrieving the new colored image and updating. It would be ideal if these events were to trigger after the values have changed on the layer's options object. (Breakpoints verify that my `onStyleChange_` function is called before `os.layer.Tile.prototype.setX`)

As a workaround for now, I can store the old value on this event and then update whatever changed after listening for the `PropertyChangeEvent` that would be fired.

**Comment by jkae** [comment]
It might also be useful for the style change event to have a `newValue` field? A few event types use that, so it seems strange this doesn't.

**Comment by wallw-bits** [comment]
There's a difference between the OpenLayers events and the OpenSphere `PropertyChangeEvent` (which does have the new value). I'll address the event order being incorrect but mixing into the OpenLayers event API should probably be a separate discussion.
