### ISSUE TITLE
Encoding detection does not properly handle non-breaking spaces

### ISSUE THREAD

**Issue by wallw-bits** [ngageoint/opensphere#1096]
I think we could update `jschardet` to pick up the fix for #674, but the latest version still fails to detect `'\u00A0'` as UTF-8. I think a better solution would be to use a more robust library such as the ones used by the browser ([`chardetng`](https://github.com/hsivonen/chardetng) or [`compact_enc_det`](https://github.com/google/compact_enc_det)). Unfortunately those aren't directly exposed via JS but it is simple enough to wrap them in Web Assembly and drop them in.

**Comment by bradh** [comment]
Is this no longer needed because of the new wasm code detection?

**Comment by wallw-bits** [comment]
Correct.
