### ISSUE TITLE
Tests pass locally but not in Travis

### ISSUE THREAD

**Issue by wallw-bits** [ngageoint/opensphere#11]
See this branch/build

https://travis-ci.org/wallw-bits/opensphere/builds/323019995

The first commit there addresses a small wait issue, but the results still differ from local test runs on OSX (same version of Chrome).

**Comment by bradh** [comment]
I'm seeing those (see #6 and #7) locally on Ubuntu 17.10.

**Comment by wallw-bits** [comment]
I was able to recreate in an Ubuntu docker image. Tests are passing in RHEL6, RHEL7, and OSX.
