### ISSUE TITLE
Screenshot capability may move overview dialog and overview results

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#124]
![image](https://user-images.githubusercontent.com/174642/36067655-5c11c6f4-0f15-11e8-8d24-83c846b8f8db.png)

with Save->Screenshot produced:
![screenshot 2018-02-11_102043](https://user-images.githubusercontent.com/174642/36067672-c26637aa-0f15-11e8-99e5-1c2e0672e5a3.png)

Two issues:
 1. that the overview map has relocated on the map (potentially obscuring object of interest)
 2. that the overview map area of interest (the dashed red box) is now showing the wrong area (north and west of the actual area in the screenshot).

**Comment by wallw-bits** [comment]
I was not able to reproduce with Chrome 63 or Firefox 57. Can you provide some additional information to reproduce such as browser version, data that was loaded, etc. and also check Windows > Log and the browser console for errors?

**Comment by bradh** [comment]
I don't usually screenshot, but pretty sure the client was Chrome 63 (which is currently updating itself) on Windows 10. Data was some shapefiles from the FAA. Will try to build a full repo.

**Comment by bradh** [comment]
It doesn't seem to be data dependent - can reproduce without any data loaded, after a reset settings.
Chrome is now version 64.0.3282.167 (Official Build) (64-bit), on Windows 10.

The relocation of the overview map only happens in the 2D map. The offset of the focus area (red dashed line highlight box) happens with 3D and 2D globes (the 3D version is a bit wacky - huge overview map in the screenshot).
![screenshot 2018-02-21_092119](https://user-images.githubusercontent.com/174642/36452642-75da3ca2-16e9-11e8-8378-1863e1e31ce7.png)

It doesn't seem to be location dependent - at the origin, I still see the offset to the north and west. Nothing related in the browser console or log that I can see.

I do have high DPI display, but other than that, its a pretty basic setup.

Would a screen recording of the exact steps I'm using help?

**Comment by wallw-bits** [comment]
If you have a high DPI display, what does `window.devicePixelRatio` report in the browser console? If that is the difference, I can test it with my laptop.

**Comment by wallw-bits** [comment]
That's probably it then. I'll run through this again on a different display.

**Comment by bradh** [comment]
Thanks - that works well for me.
