### ISSUE TITLE
Upgrade Jasmine to 3.0

### ISSUE THREAD

**Issue by schmidtk** [ngageoint/opensphere#133]
Our tests are using a very dated version of Jasmine and we should update them to the latest. 3.0 was recently released, but the 1.3 -> 2.x update will introduce most of the breaking changes for us.

It looks like the primary changes we'll have to make are:
* Replace `runs/waitsFor` async pattern with use of the `done` parameter.
* Update API for spies.

Here are some relevant docs for the upgrade:
https://jasmine.github.io/tutorials/upgrading_to_2
https://thejsguy.com/2015/01/29/Upgrading-Jasmine-from-1.3-to-2.1.html

**Comment by schmidtk** [comment]
After poking around at this a bit more, I decided to close it as "won't fix" for this iteration of OpenSphere.

The `done` callback isn't a perfect replacement for `waitsFor/runs` for cases where we don't have an event or promise to indicate when the condition has been met. `goog.async.ConditionalDelay` can help with that, and we could probably polyfill those functions if we really wanted to, but I'm not sure it's all worth the effort. This would also impact all applications depending on OS and reusing some of its testing utilities.

If anyone feels this is actually worth the fairly sizable effort, feel free to reopen.

**Comment by bradh** [comment]
I see https://github.com/ngageoint/opensphere/blob/master/package.json#L199 says `"jasmine-core": "^2.5.2",` - is that something different?

**Comment by schmidtk** [comment]
I don't believe that's actually used, but I'll look into it. I wasn't aware of this until today, but looking at the [`karma-jasmine`](https://github.com/karma-runner/karma-jasmine) docs:

- 0.1.x uses Jasmine 1
- 0.2.x uses Jasmine 2
- 0.3.0+ does not bundle Jasmine, instead requiring `jasmine-core` at the desired version

**Comment by schmidtk** [comment]
Confirmed. Our `jasmine-core` dependency is not used. I'll open a PR to remove it.
