### ISSUE TITLE
Support writing KML Track/MultiTrack

### ISSUE THREAD

**Issue by schmidtk** [ngageoint/opensphere#134]
Add track support to the KML exporter. Use the `gx:` extension for now, since we always export as KML 2.2. We could allow the user to choose 2.2 or 2.3, but that's currently not very useful because even Google Earth won't parse it.

This is blocked by #115.

**Comment by bradh** [comment]
Should that be "since we always export as KML 2.2"?

**Comment by schmidtk** [comment]
Yes, thanks. Edited.
