### ISSUE TITLE
Fix drawing tools escape

### ISSUE THREAD

**Issue by csgibson** [ngageoint/opensphere#150]
If a user hits the escape button while drawing to cancel drawing something that they did not intend to draw, it breaks the drawing tools and map menus.

**Comment by schmidtk** [comment]
Confirmed, thank you!

**Comment by schmidtk** [comment]
@csgibson Did you see this for drawing tools other than a box? I fixed the bug there, and all other draw interactions (circle, polygon, line, measure) seemed to work as expected.

**Comment by csgibson** [comment]
Sorry, it was only box. Thanks!
I also noticed another little bug that I'll throw in another issue
