### ISSUE TITLE
Implement 2D mode contrast, saturation and brightness controls

### ISSUE THREAD

**Issue by jsalankey** [ngageoint/opensphere#157]
Since Openlayers does not natively support these functions, they were taken out a long time ago and only shown in 3D since Cesium does natively support them. 

Tile coloring is implemented through the `IFilterableTileSource` interface and mixins to `ol.source.TileImage`. We can implement these 3 features as filters run through that interface.

This should also be able to clean up some of the layer UI checks for whether the map is in 3D mode.

**Comment by schmidtk** [comment]
Resolved in #273.
