### ISSUE TITLE
Add conformance violations for goog.isDef

### ISSUE THREAD

**Issue by wallw-bits** [ngageoint/opensphere#165]
`goog.isDef(val)`, `goog.isNull(val)`, and `goog.isDefAndNotNull(val)` are all completely unnecessary in even the oldest browsers we have ever supported.

Make these a conformance violation and use `val !== undefined`, `val === null`, and `val !== undefined && val !== null` instead.

**Comment by schmidtk** [comment]
Those last two should be `val === null` and `val != null`.

**Comment by wallw-bits** [comment]
Correct, but I was thinking that most of those calls were `!goog.isNull(val)`.

**Comment by schmidtk** [comment]
I started looking at this as part of #245, and created [`jscodeshift`](https://github.com/facebook/jscodeshift) transforms to update the code:

https://github.com/schmidtk/opensphere-jscodeshift
