### ISSUE TITLE
Add setting to cache things that are otherwise lazy loaded

### ISSUE THREAD

**Issue by welchyd** [ngageoint/opensphere#181]
Lazy loading is great for cutting down on the application load time, but with more libraries becoming lazy loaded (loaded only when needed) it would be useful to be able to cache the application for offline use without having to guess at which parts are lazy loaded.
Ideally this would be a setting where a user can pick to load things up front, and possibly have the option to choose which things are loaded (ie may not need the GIF library, but does want Cesium)

**Comment by wallw-bits** [comment]
That's what the electron package is for.

Caching depends entirely on the deployment settings in nginx/httpd/whatever-frontend. While we simply set it to cache for the maximum period of time in our deployments, deployments using other caching schemes may expect the browser to make a request with an ETag and then return a 304.

**Comment by csgibson** [comment]
Electron is not an option for most of these users.

**Comment by wallw-bits** [comment]
You can certainly add an external plugin to either inform those users that nothing will work offline unless they have used it once online (still keep your fingers crossed though) or generate a list of templates/files and request them (I'm still not entirely sure that this will work either).

This will not be part of the core OpenSphere projects.

**Comment by wallw-bits** [comment]
> Electron is not an option for most of these users.

Kevin sent me this:

> `electron-builder` supports creating a portable build for Windows, which any user should be able to install locally.
> Or you can just generate a zip they can extract and run.
> Every OS target in `electron-builder` supports creating a zip, so as long as they can extract the thing somewhere they can use it. It’s entirely self contained.
> And once we get geopackage support, we can give them offline tiles too.
