### ISSUE TITLE
Fix Ctrl Button Interaction

### ISSUE THREAD

**Issue by csgibson** [ngageoint/opensphere#184]
Fix the ctrl + double-click interaction. It seems to break hit detection entirely. Refresh will restore things to working order.

**Comment by brelsftm** [comment]
I can't reproduce this using ctrl + double click on macos w/ chrome.

**Comment by schmidtk** [comment]
On macOS, any interaction that uses Ctrl on Windows should use Command instead. With respect to this issue, Ctrl+double-click zooms out without causing the bug. Command+double-click does not zoom out but does cause the bug.

We should:
- Update any interactions using Ctrl on macOS, so they use Command instead.
- Prevent interactions from getting stuck (likely this is `ol.ViewHint.INTERACTING` being set but not un-set, which disables hit detection, tile loading, and other things).
- Display the correct key in the Controls window on macOS, and fix the background (needs `.modal-body`).

**Comment by brelsftm** [comment]
Fixed bullet point 3 & 4 , working on 1 & 2
