### ISSUE TITLE
Map "up" and 2D/3D buttons overlap zoom (high DPI)

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#234]
On a high DPI screen (probably causal, but not proven), I see the "map up" arrow overlap the zoom control by about 10-20%, and the 2D/3D button overlap the map up button slightly.

**Comment by wallw-bits** [comment]
All of those elements are positioned by CSS, which is abstracted away from High DPI screens by the browser (generally that only affects stuff drawn to the canvas in OpenLayers/Cesium).

Can you please attach a screenshot of the issue? I'll see if I can recreate tomorrow.

**Comment by bradh** [comment]
I'm seeing:
![image](https://user-images.githubusercontent.com/174642/39026626-6498c690-4491-11e8-984b-d23d4cd58f6e.png)

**Comment by bradh** [comment]
It is 100% (Chrome and Firefox). Changing that doesn't appear to make any difference to the proportion of the overlap.

There is a display zoom setting at the Windows level, set to 250% (Recommended). Resetting that to 100% and restarting the browser didn't seem to make any difference.

**Comment by wallw-bits** [comment]
We are not able to recreate this issue on retina screens (`devicePixelRatio` of 2.0). Like I said previously, I doubt this is a High DPI issue.

**Comment by bradh** [comment]
I'm running on Windows 10, Dell XPS 15 laptop hardware. I also see on Windows 10 on a Dell XPS 13 laptop. I don't see it on Windows 10 on my desktop.

I don't think it is a local build issue - I see in on the surge.sh instance too.

Its a pretty minor aesthetic issue, probably not worth spending much time on.

**Comment by schmidtk** [comment]
@bradh If you have a moment, could you confirm if this is still an issue? We upgraded OpenSphere to Bootstrap 4, so the CSS has changed quite a bit.

**Comment by schmidtk** [comment]
Thanks for checking! I'll leave this open so we can look into fixing it.

The minimap may be broken due to a change with how we handle min/max zoom for tile layers. I'm curious if a settings reset will resolve it for you or not. The Angular text in the search box seems to only be a problem when building outside a Yarn workspace so we didn't notice it locally. I'll get that fixed.

**Comment by bradh** [comment]
Reset of settings made the minimap return to normal. Impressive analysis!

**Comment by bradh** [comment]
I'm no longer seeing this on the same hardware.
