### ISSUE TITLE
WebGL canvas is black when capturing in 3D mode

### ISSUE THREAD

**Issue by jsalankey** [ngageoint/opensphere#268]
Capturing screenshots and GIFs is producing blank images in 3D mode. The code to get the image data from the WebGL context appears to function normally, but sometimes returns nothing but an black canvas (other elements like the map chip and timeline still capture normally). There are no exceptions being thrown and I'm seeing it across multiple browser versions.

It happens fairly consistently in both Chrome 67 and FF60, but I do occasionally get successful captures. If I capture right after loading into 3D, it works properly. But if I pan/zoom the map even a little bit, all subsequent shots will be empty. It sometimes seems to come back after that, but I don't know why.

**Comment by schmidtk** [comment]
This has been resolved.
