### ISSUE TITLE
Vector Tiles support url/dataset/z/x/y.pbf  

### ISSUE THREAD

**Issue by techmavengeospatial** [ngageoint/opensphere#297]
Can you add vector tile XYZ url ? Trying to understand supported formats.

**Comment by wallw-bits** [comment]
As a user? Not currently. You would need to add or write a plugin for that format. Our current XYZ support is limited to raster tiles.

**Comment by bradh** [comment]
@wallw-bits  / @schmidtk I think this can be closed based on https://github.com/ngageoint/opensphere/pull/1035
