### ISSUE TITLE
Most recent does not work with timeline open

### ISSUE THREAD

**Issue by swtyler** [ngageoint/opensphere#313]
The right-click 'Most Recent' option does not behave the same with the timeline open.

The current implementation requires the user to close the timeline, choose most recent (which shifts the date at the top toolbar), and re-open the timeline. If the timeline is closed, most recent will always shift the date.

This is a minor bug but it would be nice for it to work with the timeline.

**Comment by schmidtk** [comment]
This has been resolved.
