### ISSUE TITLE
Support custom WMS/WFS parameters through the import UI

### ISSUE THREAD

**Issue by csgibson** [ngageoint/opensphere#325]
This wms server seems like it might be pretty interesting but opensphere trims the request url in a way that the server doesn't like. `mapserv?map=/maps/mars/mars_simp_cyl.map` is required but omitted.

`https://planetarymaps.usgs.gov/cgi-bin/mapserv?map=/maps/mars/mars_simp_cyl.map&service=WMS&request=GetCapabilities`

**Comment by wallw-bits** [comment]
First of all, the `map` parameter is outside of the WMS spec (so shame on them; Geoserver does this much better).

That being said, the `OGCServer` provider supports custom WMS and WFS parameters. This is how we make use of services which only support WMS version 1.1.1. You just need to add a way to retrieve them off the incoming URL or enter them explicitly in the OGC Server Import UI. Right now the only way to add those custom parameters is to add the server through config.
