### ISSUE TITLE
OS should support geopackage vectors

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#36]
Might be too heavy to expose every feature in every geometry table - perhaps needs custom import logic. 

https://github.com/ngageoint/geopackage-js would be a candidate helper.

**Comment by wallw-bits** [comment]
Yeah. I sit about 20 ft from the guy who made that. The general consensus over here was that geopackage was beyond the scope of the web application because it was mostly being used for supplying maps (in addition to data) for disconnected clients, which made the files in the multi-GB range. I believe the desktop app supports that whole spec.

That being said, vector data should work just fine. As long as we make it clear that raster data isn't supported.

**Comment by bradh** [comment]
I'm having a try at the implementation (have the plugin scaffolding, but the externs are new to me, so that is taking a while).

Concur on the vectors vs tiles. The path for tiles would likely be for the client to pass a URL to the server, and the server would serve them up as required (somehow: could be directly, could REST API into geoserver, depends on server side impl).

The OGC is also working on a "related tables' extension, where you can attach media (photos, documents) to features. That might work OK too.

Speaking of desktop app, the repo is still pretty empty...

**Comment by bradh** [comment]
Because it doesn't (usually) hurt to ask, any chance that Daniel would do the compiler externs for geopackage-js?

**Comment by wallw-bits** [comment]
I'm gonna say that's highly unlikely but I'll ask. In general we typically end up writing all our own externs for libraries. You don't even have to write the whole thing, just the parts you use. Although it is pretty cool for the next guy if you do write them all.

Also, I'm not responsible for the Desktop app in any way. But I can go poke their team lead and see what's up.

**Comment by wallw-bits** [comment]
> if someone wants to submit a pull request i will totally take it - Dan

If you write them and put them in geopackage-js then they will be more widely available than if they stay buried in our `externs/` folder.

**Comment by danielbarela** [comment]
@bradh I have no experience with the compiler externs that you are talking about, however, if you create what you need and add it to the geopackage-js project I will accept it and push a new version to npm.

**Comment by bradh** [comment]
We now have the plugin, so consider this solved.
