### ISSUE TITLE
Scale icon size at low camera zoom levels

### ISSUE THREAD

**Issue by justin-bits** [ngageoint/opensphere#374]
Google Earth scales icons (after a certain threshold) as the camera zoom is reduced.  Recommend adding this capability OpenSphere.

Note in this example how the icons are much smaller in Google Earth than OpenSphere.  Depending on the number of features and icon selection, the icons can end up completely covering the globe in OpenSphere as the camera is zoomed out.  With Google Earth, the icons become smaller, then eventually disappear.  They never end up covering the globe.
![google earth](https://user-images.githubusercontent.com/44378016/50614736-11a31480-0e9f-11e9-8199-7ce5583862c2.png)
![opensphere](https://user-images.githubusercontent.com/44378016/50614737-11a31480-0e9f-11e9-8ab7-2e192b22b341.png)

**Comment by justin-bits** [comment]
[Fire Stations Features.kmz.zip](https://github.com/ngageoint/opensphere/files/2722208/Fire.Stations.Features.kmz.zip)

**Comment by csgibson** [comment]
This makes the places I have saved on my map look like bad pixels or something when zoomed all of the way out. i.e. no label and tiny size.

Can we make them just slightly bigger so they look like a thing on the map?
