### ISSUE TITLE
Remove dependency on third party server

### ISSUE THREAD

**Issue by justin-bits** [ngageoint/opensphere#398]
Per @wallw-bits from https://github.com/ngageoint/opensphere/pull/390:

> The GeoServer and Arc tests need to be refactored to spin up a container and hit that rather than depending on third-party services for tests (this should be easy for GeoServer, possibly less easy for Arc -- but there are better options for live servers there than a local gov one). Additionally, the state file test is also depending on a third-party server when it doesn't have to

**Comment by justin-bits** [comment]
We might just want to stub out the server responses instead: https://docs.cypress.io/guides/guides/network-requests.html

**Comment by wallw-bits** [comment]
That would be best in my opinion. We commonly do that for unit tests already.

**Comment by justin-bits** [comment]
https://github.com/ngageoint/opensphere/pull/481/

**Comment by bradh** [comment]
Is anything more needed on this post #481?

**Comment by justin-bits** [comment]
Nope
