### ISSUE TITLE
Scroll bars are not appearing on dialogs when dialog extends off screen

### ISSUE THREAD

**Issue by justin-bits** [ngageoint/opensphere#422]
The OK/Cancel (etc.) buttons should always be visible.  The inner portion of the dialog should have a scroll bar present.

![dialogs missing scroll bars](https://user-images.githubusercontent.com/44378016/53657021-38b56280-3c12-11e9-93a6-e6292ad013ae.png)

The is affecting numerous dialogs.

**Comment by schmidtk** [comment]
This is a combination of the directive for the window content not using `replace: true`, which adds an extra element that is not a flex container, and the root element in the template not having `d-flex flex-column`. Fixing all I can find.
