### ISSUE TITLE
Column Associations form validation and descriptor clean up issues

### ISSUE THREAD

**Issue by justin-bits** [ngageoint/opensphere#454]
- OK button disabled even though the form is filled out correctly.  Server: https://gdp-geoserver.dev.dev.east.paas.geointservices.io/geoserver/ows
![ok disabled](https://user-images.githubusercontent.com/44378016/55015086-cf770400-4fb1-11e9-8c67-d53fb2bc0f0c.png)

- Form incorrectly indicating layers are duplicated.  Server: https://ags.auroragov.org/aurora/rest/services/OpenData/MapServer
![duplicate](https://user-images.githubusercontent.com/44378016/55014985-9dfe3880-4fb1-11e9-9ee1-1b19ea0293f5.png)

- Layers from inactive or removed servers still present.
![old descriptors](https://user-images.githubusercontent.com/44378016/55014888-68594f80-4fb1-11e9-8095-67be47d12fe9.png)

**Comment by robertbolan-bits** [comment]
I will look into this one

**Comment by welchyd** [comment]
Will column associations work across servers? (ie doing a mapping between WFS and Arc)

**Comment by schmidtk** [comment]
> Will column associations work across servers? (ie doing a mapping between WFS and Arc)

Yes, they should. They map columns representing the same data (altitude, identifier, etc) between layers, which is not impacted by the server type.
