### ISSUE TITLE
Date format does not respect browser (or server locale)

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#46]
Always appears in US date format (MM/DD/YYYY).

If its fixed format, its should be ISO (YYYY-MM-DD), but ideally it would respect the browser locale.

**Comment by wallw-bits** [comment]
Dates and times displayed in the application should always be in ISO-8601. I assume you are referring to the date formats in the Angular ui-date instance in `views/datetime/wheeldate.html` (which appears in several places throughout the application).

I would hope that library has a way to send it a formatter.

**Comment by bradh** [comment]
The jquery datepicker does have a format option, we're just not using it.

Also needs a minor change to the selection logic. 

Working on the PR now.

**Comment by bradh** [comment]
Making it use the browser locale would mean parsing the format string (I had optimistically thought that the format would be 1:1 with the text length so we could just check what letters matched the selected range, but unfortunately, not the case). I'm good with ISO-8601 for now.
