### ISSUE TITLE
Saved Places Disappearing Label

### ISSUE THREAD

**Issue by csgibson** [ngageoint/opensphere#464]
Saved places labels can disappear. 
To reproduce:

1. Right Click
2. Save a place
3. Repeat a couple of times
4. Click on one to select it
5. Uncheck the "Saved Places" box in the layers window
6. Recheck it
7. The label on the selected one is gone

**Comment by schmidtk** [comment]
This appears to be fixed, or at least the eye visibility toggle doesn't cause it. #1404 is also enabling layer-wide hit detection on Saved Places and separating the feature-level flag to force label visibility, which should resolve conflicts between the Always Show checkbox and label show/hide state.
