### ISSUE TITLE
Load tiles using the request stack

### ISSUE THREAD

**Issue by justin-bits** [ngageoint/opensphere#484]
- Allows requests to be cancelled on layer removal, date change, timeline update, zoom change
- Allows requests to be stubbed in Cypress tests

**Comment by justin-bits** [comment]
Cypress part of this ticket OBE. Remainder may still be valid.

**Comment by schmidtk** [comment]
Thanks Justin. The rest we don't want to do for browser caching purposes. This would be much slower than the current approach.
