### ISSUE TITLE
Hide Annotation Button

### ISSUE THREAD

**Issue by welchyd** [ngageoint/opensphere#495]
In annotations - add an icon next the the edit button to allow a user to quickly hide an annotation. This should effectively uncheck the annotation node in the layers window when clicked.

<img width="1181" alt="Screen Shot 2019-04-24 at 12 16 43 PM" src="https://user-images.githubusercontent.com/35077650/56683671-44119100-668b-11e9-8786-ea9c3fcb663b.png">

THIN-13365
1 story point

**Comment by lilysikes** [comment]
Fixed via #502

**Comment by mgettman** [comment]
looks good
