### ISSUE TITLE
A sample / template plugin would be useful

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#52]
It isn't obvious what "best practice" is for an opensphere plugin. It might be useful to have an example one.

**Comment by bradh** [comment]
Thanks - I'll turn that into a PR against [the plugin guide](https://github.com/ngageoint/opensphere/blob/master/PLUGIN_DEVELOPMENT.md) if you're happy with that.

Do we have any plugin support for near real time feeds (like ADS-B, AIS, or CoT)?

**Comment by wallw-bits** [comment]
There is no built-in support for those feeds. However, we have successfully implemented an external plugin for similar feeds/streams in plugin in our private repository, so it should be doable.

**Comment by bradh** [comment]
I think that is enough for this task. I'll raise a separate ticket for the feed-based plugin API / example implementation.
