### ISSUE TITLE
Shape Fill Control

### ISSUE THREAD

**Issue by welchyd** [ngageoint/opensphere#531]
When drawing a shape, the user should be able to pick the fill color and opacity (numeric value)
Add this as a style control to the Add/Edit places dialog accordion
Fill is used in two places currently (preview for creating a buffer and creating an area from coordinates) so the capability just needs to be exposed and applied to shapes in general
THIN-13361
5 story points

**Comment by smithtb** [comment]
This is THIN-13361

**Comment by welchyd** [comment]
Updated

**Comment by bradh** [comment]
Given #693, I think this could be closed.

**Comment by schmidtk** [comment]
Good call, thanks @bradh.
