### ISSUE TITLE
Annotation Inline Edit

### ISSUE THREAD

**Issue by welchyd** [ngageoint/opensphere#536]
Investigate using inline library line Quill, Alloy, or Froala - something lightweight for editing annotation text like PowerPoint
Also investigate a simple control for editing the style of an annotation (ie color)
THIN-13368
2 story points

**Comment by tusotjl** [comment]
This is in dev review, spoke with both Greg and Will, the research was already done to redo / replace SimpleMDE with ToastUI. Please reference THIN-12720. Reviewed the existing examples for ToastUI and it seems to allow the "inline" editing desired features.
https://ui.toast.com/tui-editor/
