### ISSUE TITLE
Annotations do not revert to initial state after clicking cancel 

### ISSUE THREAD

**Issue by robertbolan-bits** [ngageoint/opensphere#573]
After making edits to an annotation, if you click the cancel the changes are not reverted back to the initial settings before making any edits.

**Comment by robertbolan-bits** [comment]
I will work on this

**Comment by tusotjl** [comment]
This issue was seen in a ticket that I'm currently working. I don't want to have duplicate work. I'm close to pushing to my existing PR.

**Comment by tusotjl** [comment]
THIN-13366

**Comment by tusotjl** [comment]
nevermind, I talked to jeremy, since this is a separate issue then my ticket, we don't want it holding up mine. thanks

**Comment by tusotjl** [comment]
you might want to checkout the placemarkedit.js file in opensphere it's inheriting from featureedit

**Comment by welchyd** [comment]
Closed via #605
