### ISSUE TITLE
Refactor Cypress selectors

### ISSUE THREAD

**Issue by justin-bits** [ngageoint/opensphere#580]
https://github.com/ngageoint/opensphere/pull/567#issuecomment-497756988

- Break `selectors.js` into multiple files
- Create generic selectors for commonly used elements (e.g OK button)
- Update tests accordingly to reference updated selectors

**Comment by justin-bits** [comment]
This is in progress here: https://github.com/justin-bits/opensphere/tree/test/refactor-selectors

**Comment by justin-bits** [comment]
Fixes that were in #622 and #623 are included in the work for this branch.

**Comment by justin-bits** [comment]
PR #677

**Comment by bradh** [comment]
When we originally discussed this, I thought the approach was that selectors that are only used in a single test set would be kept with the using code. Did that change?

**Comment by justin-bits** [comment]
Selectors are generally all expected to be used by more than one spec file and should be shared.

In this case, additional spec files will eventually be created for testing with other types of data and multiple instances of the dialog.
