### ISSUE TITLE
Upgrade eslint to 6.x

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#587]
Looks like this change (actually from 3.x->4.0) will hit some indent problems, and some "no multiple space" problems in the current code base. Those will need to be fixed before or as part of the upgrade.

**Comment by schmidtk** [comment]
I believe @wallw-bits started looking into this. ESLint deprecated support for JSDoc parsing, so we'll have to ensure the update doesn't lose existing lint checks. https://github.com/gajus/eslint-plugin-jsdoc seems to be the commonly accepted solution to continued JSDoc linting.

**Comment by schmidtk** [comment]
Looks like ESLint 6.0.0 was [recently released](https://eslint.org/blog/2019/06/eslint-v6.0.0-released). Changing the title to reflect that.

**Comment by bradh** [comment]
I recently tried the upgrade on my plugin and saw no (new) problems).

In terms of jsdoc rules, is the "recommended" set from https://github.com/gajus/eslint-plugin-jsdoc a reasonable starting point? Obviously will have to check it doesn't cause mass breakage or make the code ugly.

**Comment by bradh** [comment]
https://github.com/bradh/eslint-config-opensphere/commit/a961894f015356cc50ddc186cc2d71cf839a48d8 is an initial set of config changes, and https://github.com/ngageoint/opensphere/pull/634 for the indent and other cleanups.

**Comment by bradh** [comment]
Resolved by #634
