### ISSUE TITLE
Add/Edit place dialog position needs to handle small browser size better

### ISSUE THREAD

**Issue by welchyd** [ngageoint/opensphere#592]
When I have the Add/Edit place dialog open and shrink the browser size, the position dialog text overlaps the input and the globe button background shrinks. 
This needs to be fixed so the text/input don't overlap and the globe button background doesn't shrink.

![badShrink](https://user-images.githubusercontent.com/35077650/58822350-861be400-85f4-11e9-89bb-24871fa984ab.png)

THIN-12197
1 story points

**Comment by welchyd** [comment]
While you're looking at that, could you fix some other things as well?
![WhiteBG](https://user-images.githubusercontent.com/35077650/59218214-ea065580-8b7c-11e9-80a8-dc1f1b25e5c5.png)

**Comment by mgettman** [comment]
Good to go.

**Comment by welchyd** [comment]
Fixed by #619
