### ISSUE TITLE
Switch to new type inference algorithm in compiler

### ISSUE THREAD

**Issue by wallw-bits** [ngageoint/opensphere#61]
The Closure Compiler has a new type inference algorithm that produces warnings that arguably should be produced by the old algorithm but are not. We would like to switch to that new algorithm, but it is going to take going through the code and cleaning up many, many new warnings that the compiler produces with that option.

As an example, NTI (as referred to by the compiler project) would have prevented #45 from occurring in the first place. This particular issue was also opened with the compiler at https://github.com/google/closure-compiler/issues/2783.

**Comment by schmidtk** [comment]
@wallw-bits it looks like they [removed NTI from the compiler](https://github.com/google/closure-compiler/wiki/%5BOBSOLETE%5D-Using-NTI-(new-type-inference)). Should we close this?

**Comment by wallw-bits** [comment]
Yup
