### ISSUE TITLE
Turn off drag select of text

### ISSUE THREAD

**Issue by welchyd** [ngageoint/opensphere#616]
Sometimes clicking/dragging my mouse cursor in Open Sphere highlights the text
We used to block this from happening and it seems to have come back since upgrading to bootstrap 4 - let's turn this off again.
One way I'm able to get this to happen consistently is to mouse down on an input label (ie Name in the picture) and drag the cursor around while keeping the mouse down state.
![DragText](https://user-images.githubusercontent.com/35077650/59454453-5bd5dd80-8dcf-11e9-8aa4-2a09c03acfdf.png)
1 story point

**Comment by adamstja** [comment]
new-week.surge.sh

**Comment by csgibson** [comment]
Commented on the commit too but I'll mention here to that this seems to highlight in a lot of places where we want it.
Example: the copy coordinates window (hover on map, press " . ", and try to copy the coordinates)

**Comment by adamstja** [comment]
updated test link : 

jobless-surprise.surge.sh

**Comment by wallw-bits** [comment]
I think the answer is "don't do that" unless it is occurring during a legitimate interaction with the application.
