### ISSUE TITLE
Handle multi-touch inputs from trackpad

### ISSUE THREAD

**Issue by csgibson** [ngageoint/opensphere#62]
Multitouch trackpad inputs should be handled to allow for pinch zoom.

**Comment by schmidtk** [comment]
@csgibson-bits, what type of trackpad? On Macs, two finger drag up/down zooms in and out already. That may be something you can configure at the system level.

**Comment by csgibson-bits** [comment]
I was just playing around and noticed that the pinch zoom that you might expect from google maps and others didn't work. It was easy to work around with the two finger scroll though

**Comment by schmidtk** [comment]
OpenLayers added this to their interaction, but we were replacing the function that handled trackpad pinch zoom and didn't get that change. We replaced the function to replace a hard-coded timeout value, but that's now an option for the interaction. Should be able to clean it up and add the trackpad zoom.
