### ISSUE TITLE
Accordion menu sticking open

### ISSUE THREAD

**Issue by welchyd** [ngageoint/opensphere#630]
In the layers window the accordion menus have a tendency to want to be open after they have been clicked on once before - we need to have them stay closed once they've been closed

To get this to happen:
Click on a feature or map layer in the layers menu
Click on Style to open the style menu
Click on Style again to close it
Now click on a different layer
The style menu magically opens again

**Comment by welchyd** [comment]
@justin-bits, @wallw-bits this behavior seems intentional since it's saving which tab is open to settings here: https://github.com/ngageoint/opensphere/blob/master/src/os/ui/layer/defaultlayerui.js#L459
Do we want to change that behavior? Is this actually a problem?

**Comment by justin-bits** [comment]
I find it annoying as a user, so I'd say to change it.

**Comment by wallw-bits** [comment]
@welchyd if it is saving the open selection then it should also save the fact that you closed it.

**Comment by welchyd** [comment]
Okay, so it sounds like we could keep the behavior of remembering that a section is open, but also remember when a section has been closed
