### ISSUE TITLE
Annotations/places should be added to the clear menu

### ISSUE THREAD

**Issue by swtyler** [ngageoint/opensphere#632]
Please add the option to remove annotations, all saved places, or both from this menu:

![Screen Shot 2019-06-24 at 9 22 54 AM](https://user-images.githubusercontent.com/10479544/60031385-e2a57880-9661-11e9-9cf7-290fc84e883d.png)

Do what we do for areas, _turn them off, don't actually remove them_. The most common action with the clear button is to check all and we don't want people to accidentally remove all of the places they have painstakingly created.

**Comment by wallw-bits** [comment]
I think continuing to differentiate between "annotations" and "places" is a bad move. All annotations are places. Annotations are just a display option for a place.

**Comment by swtyler** [comment]
Agreed - shouldn't differentiate, I also put in a note to turn them off like areas rather than remove them.
