### ISSUE TITLE
Dash border select doesn't look consistent

### ISSUE THREAD

**Issue by welchyd** [ngageoint/opensphere#639]
When picking a border style, the select doesn't show the style consistently between browsers and operating systems. Find a way to give it a consistent look. This could be something like using a select2 and svg elements to show the line dashes

![DashSelectStyles](https://user-images.githubusercontent.com/35077650/60222413-847fbd80-983a-11e9-96d5-9731eb835434.png)

**Comment by mgettman** [comment]
Looks good.
