### ISSUE TITLE
Auto-complete background doesn't match theme

### ISSUE THREAD

**Issue by welchyd** [ngageoint/opensphere#655]
When selecting from a suggested option, the background to the selection doesn't match the theme.
Also, once a recommendation is selected the background doesn't match the theme

![selection](https://user-images.githubusercontent.com/35077650/60833774-49f01c00-a17c-11e9-99d9-4af70bcb0001.png)

Story points: 1

**Comment by schmidtk** [comment]
That suggestion dropdown is a browser `input` UI, that I don't believe we have control over. It's definitely not our UI.

**Comment by welchyd** [comment]
It seems possible to me - https://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete

**Comment by schmidtk** [comment]
Cool! Do non-Webkit browsers also support that? It looks like Firefox maybe supports an `:autofill` pseudo-selector?

https://wiki.mozilla.org/CSS/:autofill
