### ISSUE TITLE
KML import has corrupted degree symbol rendering for info

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#674]
I exported a track file from Places tab on the Layer menu, and on re-import, it has corrupted rendering of the degree symbol.

![image](https://user-images.githubusercontent.com/174642/61168330-f7ee3280-a58f-11e9-8f8e-561323d98231.png)

The exported file is attached
[Cookbook track.kml.txt](https://github.com/ngageoint/opensphere/files/3388543/Cookbook.track.kml.txt)

This is also reproducible as a standard file open, and is also visible in the "Show Features" grid.

**Comment by wallw-bits** [comment]
`jschardet` is reporting the detected character encoding as `EUC-KR`, which is definitely incorrect (should be UTF-8).

**Comment by wallw-bits** [comment]
This is detecting correctly for me today locally on `master`. @bradh can you check it out again?

**Comment by bradh** [comment]
Still happening on https://master-branch-opensphere-ngageoint.surge.sh/ with the original file.

**Comment by glennkitchellcaci** [comment]
Submitted ticket with jschardet.
https://github.com/aadsm/jschardet/issues/50
Probably nothing will come of it so we may have to add some additional handlers of our own.

**Comment by wallw-bits** [comment]
@glennkitchellcaci did you try upgrading jschardet to 2.1.0?

**Comment by bradh** [comment]
Can no longer reproduce. I didn't try to find the specific fix, but likely associated with the new chardet work.
