### ISSUE TITLE
Validate multipolygons as separate polygons

### ISSUE THREAD

**Issue by wallw-bits** [ngageoint/opensphere#701]
JTS (and therefore JSTS) validates MultiPolygons according to the [constraints mentioned here](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/MultiPolygon.html). On our end, the rendering does not care one bit about that and all polygons in a multipolygon are processed and rendered as separate polygons. Therefore, they should be validated in a similar manner.

Adjust `os.geo.jsts.validate()` and/or `os.feature.validateGeometries()` accordingly. [Here's a sample file](https://github.com/ngageoint/opensphere/files/3428763/altitude_box.txt) that should work for testing.

**Comment by schmidtk** [comment]
Resolved by fcf4dce. `os.geo.jsts.validate` still doesn't break up a MultiPolygon, but it's probably best to leave that decision outside the JSTS module.
