### ISSUE TITLE
Add jest dependency

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#724]
yarn reports:

```
warning "workspace-aggregator-7997fbc4-b19f-4ddf-aac2-ee6a8b8fd831 > opensphere > cypress-image-snapshot > jest-image-snapshot@2.8.2" has unmet peer dependency "jest@>=20 <=24".
```

**Comment by schmidtk** [comment]
[`cypress-image-snapshot`](https://www.npmjs.com/package/cypress-image-snapshot) is using code from `jest-image-snapshot` in a way that doesn't depend on `jest`. This warning can be ignored.
