### ISSUE TITLE
Toolbar buttons overlapping

### ISSUE THREAD

**Issue by justin-bits** [ngageoint/opensphere#732]
Bug against OS. Some tests failing due to overlapping buttons:
```
CypressError: Timed out retrying: cy.click() failed because this element:

<button id="timelineButton" class="btn btn-warning ml-1 flex-shrink-0 o-timeline-button" ng-click="ctrl.expand()" title="Expand to full timeline">...</button>

is being covered by another element:
```
Workaround being added to the tests until this is fixed.

See attached zipped video.  "...the buttons on the right are extending out past their parent element...so it moves the timeline controls later than it should."
[toolbar.zip](https://github.com/ngageoint/opensphere/files/3507097/toolbar.zip)

**Comment by schmidtk** [comment]
Cypress tests have been moved to an external project. This also should hopefully be fixed by our recent work to improve the nav collapse behavior.
