### ISSUE TITLE
server guide should include descriptor and importui, plus state persistence

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#84]
Without those, the "manage servers" button shows:
`Error! There is no import UI defined for "tileserver".`
 
Menu shows:
```
Provider: null
Type: Map Layer

No description provided

Tags: (none)
```

Tileserver does not stay configured through reload.

**Comment by wallw-bits** [comment]
The server guide does not need its own descriptor (it uses `os.data.ConfigDescriptor`). It does stay configured through reload provided that you added the proper configuration to `settings.json`.

I'm planning on adding steps for doing server import UIs, which will allow the user to add a server in addition to the admin adding one through config.

At no point in the guide, as it is now, should you be using Open File/URL to hit `http://localhost:<port>/index.json`.

**Comment by bradh** [comment]
Thanks. If I configure one of the layers on it appears in the Layers tab in the Layers window as expected, then reload, its gone from the tree in the Layers tab in the Layers window.  I assume the config settings can be in either `opensphere/config/settings.json` or in the plugin - behaviour on reload is unchanged. I have
```
diff --git a/config/settings.json b/config/settings.json
index 1a80e8a..123d8fb 100644
--- a/config/settings.json
+++ b/config/settings.json
@@ -119,6 +119,11 @@
       },
       "state": {
         "type": "state"
+      },
+      "tileserver-example": {
+        "type": "tileserver",
+        "label": "Tileserver Example",
+        "url": "http://192.168.40.118:8081/index.json"
       }
     },
     "search": {
```

Is something else needed to preserve state?

On the `Provider: null` part, can I have a hint on how to fix that?

**Comment by wallw-bits** [comment]
Should be fixed in https://github.com/ngageoint/opensphere/commit/75d648bfc33b4f58e1a7a35efb4d4f7462fc619b

**Comment by bradh** [comment]
Added a PR for some editorial changes (#93), but happy that this ticket needs are resolved.
