### ISSUE TITLE
Tile provider URL should support templated server names and arrays of servers

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#86]
Often we have a range of tile providers (e.g. OSM provides 3 - [a-c].tile.openstreetmap.org].

Ideally we'd be able to provide just the template.

**Comment by wallw-bits** [comment]
This is likely because there's a line like

```
var urls = options['urls'] || [options['url']];
```

Somewhere up in the tile layer configs. OpenLayers doesn't do templating if sent a `urls` array rather than `url`. Therefore, if a single `url` exists, prefer that rather than adding it as `urls` with a single entry.

**Comment by bradh** [comment]
Working on this.  The part that does the url conversion is here: https://github.com/ngageoint/opensphere/blob/master/src/os/layer/config/abstracttilelayerconfig.js#L71

However because of the cross origin support (https://github.com/ngageoint/opensphere/blob/master/src/os/layer/config/abstracttilelayerconfig.js#L112) its currently looking better to expand the URL on the OS side and always pass an array.
