### ISSUE TITLE
Implement support for KML tours

### ISSUE THREAD

**Issue by wallw-bits** [ngageoint/opensphere#88]
See http://www.opengeospatial.org/pressroom/pressreleases/2237 for the basic updates.

May need to split this into Tour and Track support separately. We have some code for tracks that we can reuse and pull into the project.

**Comment by bradh** [comment]
Is this intended to handle reading, or also support writing (e.g. select 2.2 or 2.3 for generated files)?

**Comment by wallw-bits** [comment]
Reading Tours, but potentially writing Tracks.

**Comment by schmidtk** [comment]
Changing this to add KML tour support. I'll write separate tickets for follow-on work and KML tracks.
