### ISSUE TITLE
Investigate committing overrides back to OpenLayers

### ISSUE THREAD

**Issue by wallw-bits** [ngageoint/opensphere#91]
We have several overrides to `ol.render.canvas.PolygonReplay` in `src/os/ol/mixin/render.js`.

Investigate the possibility of committing those changes back to OpenLayers and removing the mixin.

**Comment by schmidtk** [comment]
@wallw-bits - @jsalankey opened [a ticket](https://github.com/openlayers/openlayers/issues/4846) against Openlayers awhile back to fix/change this but we haven't heard anything from them. The WebGL hit detection behaves as we'd expect (doesn't detect an unfilled polygon outside of the stroke), so it shouldn't be a hard sell. I'll make a PR for them. Hopefully it gets released prior to 5.0 when they stop using Closure entirely...

**Comment by schmidtk** [comment]
Opened [a PR](https://github.com/openlayers/openlayers/pull/7750) with our changes.

**Comment by schmidtk** [comment]
My PR was merged under OpenLayers 5.x, so removing the mixin is now blocked by #245.

**Comment by schmidtk** [comment]
Upgrading OpenLayers is going to be a significant change with their move to ES6/TypeScript, so I don't think we need to keep this open. We'll have to hit all mixins in that process anyway. Closing.
