### ISSUE TITLE
Something broke template loading

### ISSUE THREAD

**Issue by wallw-bits** [ngageoint/opensphere#931]
See error on https://master-branch-opensphere-ngageoint.surge.sh/

Our people seem to think it is related to `yarn upgrade` with something released in the last day or so.

**Comment by wallw-bits** [comment]
This has been initially resolved by #932, however, further investigation needs to be made to see if a bug needs to be filed with jquery or if we should use something stricter for our html template linting.

**Comment by schmidtk** [comment]
@wallw-bits the template issues should be fixed by #1137. Can we close this?
