### ISSUE TITLE
redirect loop "localhost redirected you too many times."

### ISSUE THREAD

**Issue by sstephans** [ngageoint/opensphere#967]
I am trying to run the basic opensphere locally, without having changed anything. I'm running on windows and followed the windows development guide to install and build opensphere. 

When I run either `yarn start-server` or `npm run start-server`, navigating to http://localhost:8282/workspace/opensphere and to http://localhost:8282/workspace/opensphere/dist/opensphere each give me the redirect error. The url in the bar becomes `http://localhost:8282/workspace/opensphere//////////////////////////////////////` before my browser detects the loop and stops it.

What is going wrong with it and how can I fix it?

**Comment by bradh** [comment]
There was discussion on the Slack, and Will noted: https://github.com/http-party/http-server/issues/525 is likely the problem.
