### ISSUE TITLE
Image Layer styling doesn't have variable opacity in 3D mode

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere#994]
When using an image layer, the Styling Opacity slider works as expected in 2D mode, where zero opacity shows the background through the image overlay, and increasing opacity shows more of the overlay.

![image](https://user-images.githubusercontent.com/174642/88615156-b534c500-d0d4-11ea-9c15-3435ad420790.png)

However that doesn't work as expected in 3D mode. The slider has no effect on the displayed image. Instead, its always opaque.

![image](https://user-images.githubusercontent.com/174642/88615103-95050600-d0d4-11ea-913f-c36371042553.png)

**Comment by schmidtk** [comment]
This has been addressed, along with adding support for other image adjustments like Sharpness, Contrast, etc.
